version: '3.8'

services:
  # --- 1. EUREKA SERVER (O Registo Central) ---
  service-registry:
    build: ./service-registry/service-registry
    ports:
      - "8761:8761"
    container_name: service-registry

  # --- 2. API GATEWAY (A Porta de Entrada - 8080) ---
  api-gateway:
    build: ./api-gateway/api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    depends_on:
      - service-registry

  # --- 3. AUTH SERVICE (Autenticação - 8081) ---
  auth-service:
    build: ./auth-service/auth-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    depends_on:
      - service-registry

  # --- 4. TRIP SERVICE (Viagens - 8082) ---
  trip-service:
    build: ./trip-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    depends_on:
      - service-registry
      - auth-service

  admin-service:
    build: ./admin-service
    ports:
      - "8090:8090"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    depends_on:
      - service-registry
      - auth-service # O Admin depende do Auth para funcionar

  # --- 5. BOOKING SERVICE (Reservas - 8083) ---
  booking-service:
    build: ./booking-service
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    depends_on:
      - service-registry

  # --- 6. PAYMENT SERVICE (Pagamentos - 8084) ---
  payment-service:
    build: ./payment-service
    ports:
      - "8084:8084"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    depends_on:
      - service-registry

  # --- 7. VEHICLE SERVICE (Veículos - 8085) ---
  vehicle-service:
    build: ./vehicle-service
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    depends_on:
      - service-registry

  # --- 8. FRONTEND SERVICE (Web - 9090) ---
  frontend-service:
    build: ./frontend-service
    ports:
      - "9090:9090"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    depends_on:
      - service-registry
      - api-gateway

